# Generated by Django 3.1.3 on 2020-12-05 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201110_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='rent',
            name='car',
            field=models.ManyToManyField(related_name='car_list', to='api.Cars'),
        ),
    ]
