# Generated by Django 3.1.3 on 2020-12-05 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201205_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='is_rent',
            field=models.BooleanField(default=False),
        ),
    ]
